### ISSUE TITLE
Not an issue, Feature request. Invisible Ethereal Glass

### ISSUE THREAD

**Issue by ebaystudio** [Up-Mods/Glassential#4]
All the features of Ethereal Glass but an invisible block. It can be used to keep mobs, and villagers in specific areas of a building. For example an open-air Trading Hall of in large builds like a castle you can keep your villagers in specific areas so they dont all wander into a corner somewhere.

**Comment by ebaystudio** [comment]
Or add a mob blocking block that the player doesn't have to crouch for. A Barrier Block that only effects mobs and villagers.

**Comment by UpcraftLP** [comment]
Hey, sorry for the late reply, but being invisible kinda defeats the purpose of being glass..

However you might want to have a look at the `Entity Barrier` from [Peculiar Pieces](https://www.curseforge.com/minecraft/mc-mods/peculiarpieces), it does exactly what you are asking for!
